[workspace]
resolver = "2"
members = [
    "minotari",
    "integration-tests",
    "minotari-scanning"
]

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["The Tari Development Community"]
license = "BSD-3-Clause"
repository = "https://github.com/tari-project/minotari-cli"


[workspace.dependencies]
# TODO: switch back to a crates.io release once tari#8054 is published
tari_common = { path = "../tari/common"}
tari_common_types = { path = "../tari/base_layer/common_types" }
tari_crypto = { version = "0.23", features = ["borsh"] }
tari_utilities = { version = "0.10", features = ["std"] }
tari_script = { path = "../tari/infrastructure/tari_script" }
tari_sidechain = { path = "../tari/base_layer/sidechain" }
tari_transaction_components = { path = "../tari/base_layer/transaction_components" }
minotari_app_grpc = { path = "../tari/applications/minotari_app_grpc", default-features = false }
tari_node_components = { path = "../tari/base_layer/node_components" }
minotari-scanning = { path = "minotari-scanning", version = "0.2.0" }

[profile.release]
# By default, Rust will wrap an integer in release mode instead of throwing the overflow error
# seen in debug mode. Panicking at this time is better than silently using the wrong value.
overflow-checks = true